version: '3'

services:
  website:
    build: ./pelican
    restart: always
    entrypoint: ["pelican", "-r", "-l", "/site/content/", "-o", "/site/output", "-s", "/site/pelicanconf.py"]
    volumes:
      - ./pelican:/site
      - ./recettes:/site/content

  webhook:
    build: ./webhook-handler
    restart: always
    volumes:
      - ./webhook-handler/app:/app
      - ./recettes:/meta/recettes
    ports:
      - 8001:8001
    environment:
      - FLASK_APP=main.py
      - 'RUN=flask run --host=0.0.0.0 --port=8001'
    command: flask run --host=0.0.0.0 --port=8001

networks:
  default:
    external:
      name: nextcloud_docker_proxy-tier
