version: '3'

services:
  website:
    build: ./pelican
    restart: always
    entrypoint: ["pelican", "-d","-r", "-l", "/site/content/", "-o", "/site/output", "-s", "/site/pelicanconf.py"]
    volumes:
      - recettes:/site/content
    depends_on:
      - webhook

  webhook:
    build: ./webhook-handler
    restart: always
    volumes:
      - ./webhook-handler/app:/app
      - recettes:/meta/recettes
    ports:
      - 8001:8001
    command: waitress-serve --port=8001 --call app:create_app

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /home/manu/blogRecettes/data/certbot/conf:/etc/letsencrypt
      - /home/manu/blogRecettes/data/certbot/www:/var/www/certbot

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/manu/blogRecettes/data/certbot/conf:/etc/letsencrypt
      - /home/manu/blogRecettes/data/certbot/www:/var/www/certbot
      - ./data/nginx:/etc/nginx/conf.d
    depends_on:
        - webhook
        - website
        - certbot

volumes:
    recettes:
