version: '3'

services:
  website:
    build: ./pelican
    restart: always
    entrypoint: ["pelican", "-d", "-r", "-l", "/site/content/", "-o", "/site/output", "-s", "/site/pelicanconf.py"]
    volumes:
      - recettes:/site/content
    depends_on:
      - webhook
    ports:
      - 80:8000

  webhook:
    build: ./webhook-handler
    restart: always
    volumes:
      - ./webhook-handler/app:/app
      - recettes:/meta/recettes
    ports:
      - 8001:8001
    environment:
      - FLASK_APP=app
      - 'RUN=flask run --host=0.0.0.0 --port=8001'
    command: flask run --host=0.0.0.0 --port=8001

volumes:
  recettes:
